# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Programming Butler
email: jonmagic@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am a geek by choice and a geek by trade. I live with my family in Northern
  California where we love to cook, explore, and enjoy life. I work at GitHub
  where I solve problems with software and buttle now and again.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://theprogrammingbutler.com" # the base hostname & protocol for your site
twitter_username: jonmagic
github_username:  jonmagic

# Build settings
markdown: kramdown
